<?php
/**
 * Multi-language support
 * Поддержка нескольких языков
 * Ko'p tilni qo'llab-quvvatlash
 */

return [
    'uz' => [
        'title' => 'Maqolalar Boshqaruvi',
        'add_article' => 'Maqola qo\'shish',
        'article_name' => 'Maqola nomi',
        'author' => 'Muallif',
        'save' => 'Saqlash',
        'articles_list' => 'Maqolalar ro\'yxati',
        'id' => 'ID',
        'title_column' => 'Maqola nomi',
        'author_column' => 'Muallif',
        'created_at' => 'Qo\'shilgan sana',
        'actions' => 'Amallar',
        'delete' => 'O\'chirish',
        'search' => 'Qidirish',
        'search_placeholder' => 'Maqola nomi bo\'yicha qidirish...',
        'no_articles' => 'Hech qanday maqola topilmadi',
        'success_added' => 'Maqola muvaffaqiyatli qo\'shildi!',
        'success_deleted' => 'Maqola o\'chirildi!',
        'error' => 'Xatolik yuz berdi!',
        'required_fields' => 'Barcha maydonlarni to\'ldiring!',
        'confirm_delete' => 'Rostdan ham o\'chirmoqchimisiz?',
    ],
    'ru' => [
        'title' => 'Управление Статьями',
        'add_article' => 'Добавить статью',
        'article_name' => 'Название статьи',
        'author' => 'Автор',
        'save' => 'Сохранить',
        'articles_list' => 'Список статей',
        'id' => 'ID',
        'title_column' => 'Название',
        'author_column' => 'Автор',
        'created_at' => 'Дата добавления',
        'actions' => 'Действия',
        'delete' => 'Удалить',
        'search' => 'Поиск',
        'search_placeholder' => 'Поиск по названию статьи...',
        'no_articles' => 'Статьи не найдены',
        'success_added' => 'Статья успешно добавлена!',
        'success_deleted' => 'Статья удалена!',
        'error' => 'Произошла ошибка!',
        'required_fields' => 'Заполните все поля!',
        'confirm_delete' => 'Вы действительно хотите удалить?',
    ],
    'en' => [
        'title' => 'Article Management',
        'add_article' => 'Add Article',
        'article_name' => 'Article Title',
        'author' => 'Author',
        'save' => 'Save',
        'articles_list' => 'Articles List',
        'id' => 'ID',
        'title_column' => 'Title',
        'author_column' => 'Author',
        'created_at' => 'Created Date',
        'actions' => 'Actions',
        'delete' => 'Delete',
        'search' => 'Search',
        'search_placeholder' => 'Search by article title...',
        'no_articles' => 'No articles found',
        'success_added' => 'Article added successfully!',
        'success_deleted' => 'Article deleted!',
        'error' => 'An error occurred!',
        'required_fields' => 'Please fill all fields!',
        'confirm_delete' => 'Are you sure you want to delete?',
    ]
];
